import type { CatalogEntry } from './types';

// Snapshot: TFT Set 15 K.O. Coliseum (CommunityDragon 15.17, Aug 27 2025).
// Source: https://raw.communitydragon.org/15.17/cdragon/tft/en_us.json (setData Set15).
// Filtering rule: include Set15 source entries with apiName prefix TFT15_, cost 1-5,
// and at least one trait (the source's playable-champion metadata). Component IDs are
// the ten canonical basic components in that set; no synthesized aliases are used.
export const CATALOG: readonly CatalogEntry[] = [
  { id: 'ahri', name: 'Ahri', category: 'champion', icon: 'ahri' },
  { id: 'garen', name: 'Garen', category: 'champion', icon: 'garen' },
  { id: 'jinx', name: 'Jinx', category: 'champion', icon: 'jinx' },
  { id: 'kobuko', name: 'Kobuko', category: 'champion', icon: 'kobuko' },
  { id: 'malphite', name: 'Malphite', category: 'champion', icon: 'malphite' },
  { id: 'shen', name: 'Shen', category: 'champion', icon: 'shen' },
  { id: 'viego', name: 'Viego', category: 'champion', icon: 'viego' },
  { id: 'xayah', name: 'Xayah', category: 'champion', icon: 'xayah' },
  { id: 'yuumi', name: 'Yuumi', category: 'champion', icon: 'yuumi' },
  { id: 'zac', name: 'Zac', category: 'champion', icon: 'zac' },
  { id: 'aatrox', name: 'Aatrox', category: 'champion', icon: 'aatrox' },
  { id: 'akali', name: 'Akali', category: 'champion', icon: 'akali' },
  { id: 'ashe', name: 'Ashe', category: 'champion', icon: 'ashe' },
  { id: 'braum', name: 'Braum', category: 'champion', icon: 'braum' },
  { id: 'caitlyn', name: 'Caitlyn', category: 'champion', icon: 'caitlyn' },
  { id: 'darius', name: 'Darius', category: 'champion', icon: 'darius' },
  { id: 'ezreal', name: 'Ezreal', category: 'champion', icon: 'ezreal' },
  { id: 'gwen', name: 'Gwen', category: 'champion', icon: 'gwen' },
  { id: 'janna', name: 'Janna', category: 'champion', icon: 'janna' },
  { id: 'jarvan-iv', name: 'Jarvan IV', category: 'champion', icon: 'jarvan-iv' },
  { id: 'jayce', name: 'Jayce', category: 'champion', icon: 'jayce' },
  { id: 'jhin', name: 'Jhin', category: 'champion', icon: 'jhin' },
  { id: 'ksante', name: "K'Sante", category: 'champion', icon: 'ksante' },
  { id: 'kai-sa', name: "Kai'Sa", category: 'champion', icon: 'kai-sa' },
  { id: 'kalista', name: 'Kalista', category: 'champion', icon: 'kalista' },
  { id: 'katarina', name: 'Katarina', category: 'champion', icon: 'katarina' },
  { id: 'kayle', name: 'Kayle', category: 'champion', icon: 'kayle' },
  { id: 'kennen', name: 'Kennen', category: 'champion', icon: 'kennen' },
  { id: 'lee-sin', name: 'Lee Sin', category: 'champion', icon: 'lee-sin' },
  { id: 'leona', name: 'Leona', category: 'champion', icon: 'leona' },
  { id: 'lulu', name: 'Lulu', category: 'champion', icon: 'lulu' },
  { id: 'lux', name: 'Lux', category: 'champion', icon: 'lux' },
  { id: 'malzahar', name: 'Malzahar', category: 'champion', icon: 'malzahar' },
  { id: 'naafiri', name: 'Naafiri', category: 'champion', icon: 'naafiri' },
  { id: 'poppy', name: 'Poppy', category: 'champion', icon: 'poppy' },
  { id: 'rakan', name: 'Rakan', category: 'champion', icon: 'rakan' },
  { id: 'rell', name: 'Rell', category: 'champion', icon: 'rell' },
  { id: 'ryze', name: 'Ryze', category: 'champion', icon: 'ryze' },
  { id: 'samira', name: 'Samira', category: 'champion', icon: 'samira' },
  { id: 'seraphine', name: 'Seraphine', category: 'champion', icon: 'seraphine' },
  { id: 'sett', name: 'Sett', category: 'champion', icon: 'sett' },
  { id: 'swain', name: 'Swain', category: 'champion', icon: 'swain' },
  { id: 'syndra', name: 'Syndra', category: 'champion', icon: 'syndra' },
  { id: 'udyr', name: 'Udyr', category: 'champion', icon: 'udyr' },
  { id: 'varus', name: 'Varus', category: 'champion', icon: 'varus' },
  { id: 'xin-zhao', name: 'Xin Zhao', category: 'champion', icon: 'xin-zhao' },
  { id: 'yasuo', name: 'Yasuo', category: 'champion', icon: 'yasuo' },
  { id: 'yone', name: 'Yone', category: 'champion', icon: 'yone' },
  { id: 'ziggs', name: 'Ziggs', category: 'champion', icon: 'ziggs' },
  { id: 'volibear', name: 'Volibear', category: 'champion', icon: 'volibear' },
  { id: 'kog-maw', name: "Kog'Maw", category: 'champion', icon: 'kog-maw' },
  { id: 'smolder', name: 'Smolder', category: 'champion', icon: 'smolder' },
  { id: 'senna', name: 'Senna', category: 'champion', icon: 'senna' },
  { id: 'lucian', name: 'Lucian', category: 'champion', icon: 'lucian' },
  { id: 'gangplank', name: 'Gangplank', category: 'champion', icon: 'gangplank' },
  { id: 'dr-mundo', name: 'Dr. Mundo', category: 'champion', icon: 'dr-mundo' },
  { id: 'gnar', name: 'Gnar', category: 'champion', icon: 'gnar' },
  { id: 'karma', name: 'Karma', category: 'champion', icon: 'karma' },
  { id: 'vi', name: 'Vi', category: 'champion', icon: 'vi' },
  { id: 'sivir', name: 'Sivir', category: 'champion', icon: 'sivir' },
  { id: 'twisted-fate', name: 'Twisted Fate', category: 'champion', icon: 'twisted-fate' },
  { id: 'rammus', name: 'Rammus', category: 'champion', icon: 'rammus' },
  { id: 'zyra', name: 'Zyra', category: 'champion', icon: 'zyra' },
  { id: 'neeko', name: 'Neeko', category: 'champion', icon: 'neeko' },
  { id: 'bf-sword', name: 'B.F. Sword', category: 'component', icon: 'bf-sword' },
  { id: 'recurve-bow', name: 'Recurve Bow', category: 'component', icon: 'recurve-bow' },
  { id: 'needlessly-large-rod', name: 'Needlessly Large Rod', category: 'component', icon: 'needlessly-large-rod' },
  { id: 'tear-of-the-goddess', name: 'Tear of the Goddess', category: 'component', icon: 'tear-of-the-goddess' },
  { id: 'chain-vest', name: 'Chain Vest', category: 'component', icon: 'chain-vest' },
  { id: 'negatron-cloak', name: 'Negatron Cloak', category: 'component', icon: 'negatron-cloak' },
  { id: 'giants-belt', name: "Giant's Belt", category: 'component', icon: 'giants-belt' },
  { id: 'sparring-gloves', name: 'Sparring Gloves', category: 'component', icon: 'sparring-gloves' },
  { id: 'spatula', name: 'Spatula', category: 'component', icon: 'spatula' },
  { id: 'frying-pan', name: 'Frying Pan', category: 'component', icon: 'frying-pan' },
];
